apiVersion: apps/v1
kind: Deployment
metadata:
  name: carsunlimited-inventory-deployment
  labels:
    app: carstore-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carstore-inventory
  template:
    metadata:
      labels:
        app: carstore-inventory
    spec:
      containers:
      - name: inventory
        image: <url to image>
        ports:
        - containerPort: 80
        env:
          - name: MyApiKey
            value: "ALSOTOBEREPLACED"
          - name: StorageConnectionString
            value: "REPLACEME"
      imagePullSecrets:
        - name: <name of your secret>
